spring.application.name=Biblioteca

# Configuración para SQL Server (SQL Server Authentication)
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=biblioteca_db;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=bibliotecario
spring.datasource.password=Password123*

# Hibernate para SQL Server
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
